End points
mrparkersson/blog-app pull request #12
Opened 2022-06-17 18:42 UTC by mrparkersson

-Create an API endpoint to list all posts for a user.
-Create an API endpoint to list all comments for a user's post.
-Create an API endpoint to add a comment to a post. Remember that the owner of the comment is the user that makes it; it should not be set by passing a parameter.
-Add authentication to your API endpoints.
-Your API endpoints should receive JSON and respond JSON as well.

2022-06-17 19:29 UTC, DeliceLydia requested changes
## Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Highlights for your project:
- Awesome README
- Followed git workflow


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-17 19:29 UTC, DeliceLydia commented on app/controllers/application_controller.rb
> +  end
- [ ] I am not able to sign in it seems like there is an error while decoding a token please address that
![token](https://user-images.githubusercontent.com/44745855/174389785-4489b0d8-a494-4dde-8db1-814f5b58dbe7.png)

2022-06-17 19:33 UTC, DeliceLydia commented on app/controllers/application_controller.rb
> +  end
- [ ] I am not able to sign up or sign in there is an error while decoding a token please address that
![token](https://user-images.githubusercontent.com/44745855/174390420-06d29265-790a-4948-ba2b-1d741bab9a78.png)

2022-06-18 12:28 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @mrparkersson, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Great job so far

 ## Required Changes ♻️
- [ ] I couldn't run your app as it throws an error in the terminal when I run rails db:create; 
As I couldn't run I was not able to check previous reviewers' requirements to sign up or sign in.
<img width="1022" alt="Screenshot 2022-06-18 at 3 24 37 PM" src="https://user-images.githubusercontent.com/70269507/174437661-4874f31d-66fb-4889-9d2f-d57bad26286b.png">

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-18 13:23 UTC, mrparkersson commented
Now  rails db:create work
<img width="1440" alt="Screen Shot 2022-06-18 at 1 22 34 PM" src="https://user-images.githubusercontent.com/83285992/174439671-2e2c7bd3-0600-4ac4-9fc9-23090734108b.png">
s

2022-06-18 13:54 UTC, dasileker approved these changes
### **Hi @mrparkersson,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-18 14:22 UTC, merged